kind: Deployment
apiVersion: apps/v1
metadata:
  name: react-wordle
spec:
  replicas: 2
  selector:
    matchLabels:
      app: react-wordle
  template:
    metadata:
      labels:
        app: react-wordle
    spec:
      containers:
      - name: react-wordle
        image: kikmaster/react-wordle
        ports:
        - containerPort: 80